//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.suber_silk_serviceSoap")]
    public interface suber_silk_serviceSoap {
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertAdmin", ReplyAction="*")]
        WebApplication1.ServiceReference1.insertAdminResponse insertAdmin(WebApplication1.ServiceReference1.insertAdminRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertAdmin", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.insertAdminResponse> insertAdminAsync(WebApplication1.ServiceReference1.insertAdminRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertAdmin", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.insertAdminRequestBody Body;
        
        public insertAdminRequest() {
        }
        
        public insertAdminRequest(WebApplication1.ServiceReference1.insertAdminRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertAdminRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        public insertAdminRequestBody() {
        }
        
        public insertAdminRequestBody(string id, string name, string username, string password) {
            this.id = id;
            this.name = name;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertAdminResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.insertAdminResponseBody Body;
        
        public insertAdminResponse() {
        }
        
        public insertAdminResponse(WebApplication1.ServiceReference1.insertAdminResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertAdminResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int insertAdminResult;
        
        public insertAdminResponseBody() {
        }
        
        public insertAdminResponseBody(int insertAdminResult) {
            this.insertAdminResult = insertAdminResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface suber_silk_serviceSoapChannel : WebApplication1.ServiceReference1.suber_silk_serviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class suber_silk_serviceSoapClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.suber_silk_serviceSoap>, WebApplication1.ServiceReference1.suber_silk_serviceSoap {
        
        public suber_silk_serviceSoapClient() {
        }
        
        public suber_silk_serviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public suber_silk_serviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public suber_silk_serviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public suber_silk_serviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.insertAdminResponse WebApplication1.ServiceReference1.suber_silk_serviceSoap.insertAdmin(WebApplication1.ServiceReference1.insertAdminRequest request) {
            return base.Channel.insertAdmin(request);
        }
        
        public int insertAdmin(string id, string name, string username, string password) {
            WebApplication1.ServiceReference1.insertAdminRequest inValue = new WebApplication1.ServiceReference1.insertAdminRequest();
            inValue.Body = new WebApplication1.ServiceReference1.insertAdminRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.username = username;
            inValue.Body.password = password;
            WebApplication1.ServiceReference1.insertAdminResponse retVal = ((WebApplication1.ServiceReference1.suber_silk_serviceSoap)(this)).insertAdmin(inValue);
            return retVal.Body.insertAdminResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.insertAdminResponse> WebApplication1.ServiceReference1.suber_silk_serviceSoap.insertAdminAsync(WebApplication1.ServiceReference1.insertAdminRequest request) {
            return base.Channel.insertAdminAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.insertAdminResponse> insertAdminAsync(string id, string name, string username, string password) {
            WebApplication1.ServiceReference1.insertAdminRequest inValue = new WebApplication1.ServiceReference1.insertAdminRequest();
            inValue.Body = new WebApplication1.ServiceReference1.insertAdminRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((WebApplication1.ServiceReference1.suber_silk_serviceSoap)(this)).insertAdminAsync(inValue);
        }
    }
}
